name: Atualizar Agenda de Jogos


on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3


      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt


      - name: Executar Script de Atualização
        run: python scripts/updater.py


      - name: Fazer Commit e Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/data/nextMatch.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Atualiza agenda de jogos via Python" && git push)